# Generated by Django 2.2.6 on 2019-10-23 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('data_criada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
